### PR TITLE
Fixes url encoding

### LINKED ISSUE #144: URL encode the Jenkins plan, so that the fork reporter can point to it when generating the flakiness report

### PR DESCRIPTION
**Pull request by jbaginski**
Fixes #144

### CODE REVIEW

File: fork-common/src/main/java/com/shazam/fork/utils/NameSanitizer.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+        return buffer.toString();
+    }
+
+    @Nonnull
+    private Pattern createMatchingPattern(boolean escapeUnderscores) {
+        String pattern = "[^a-zA-Z0-9-_]";
+        if (escapeUnderscores) {
+            pattern = "[^a-zA-Z0-9-]";
+        }
+        return Pattern.compile(pattern);
```
Comment (iordanis) [inline fork-common/src/main/java/com/shazam/fork/utils/NameSanitizer.java]: Let's do this once, not with each call to this method.

File: fork-common/src/main/java/com/shazam/fork/utils/UrlEncoder.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    private UrlEncoder() {}
+
+    @Nonnull
+    public static String encodeUrl(@Nonnull String string) {
+        try {
+            return URLEncoder.encode(string, UTF_8.name())
+                    .replaceAll("\\+", "%20");
+        } catch (UnsupportedEncodingException e) {
+            e.printStackTrace();
+            return "";
```
Comment (iordanis) [inline fork-common/src/main/java/com/shazam/fork/utils/UrlEncoder.java]: Shouldn't this let the exception, instead of silently failing?
